// Generate a per-route "Sources" manifest for one site from the claims ledger.
//
// Usage:
//   node docs/claims/gen-sources.mjs <domain> <outfile.json> [--include-unverifiable]
// Example:
//   node docs/claims/gen-sources.mjs freeflyevent.com \
//     freeflyevent-site/src/data/page-sources.generated.json
//
// Reads every claim file in docs/claims/, finds usage lines for <domain>,
// extracts the public route(s) each claim appears on, and emits a JSON map
// route -> [{ id, claim, status, sources }]. Repo-path usage lines
// (e.g. "freeflyevent-site/src/data/events.ts") are skipped — public routes only.
//
// By default only status: verified claims are emitted (public "Sources" =
// facts we stand behind). Pass --include-unverifiable to also emit those.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const [domain, outfile] = process.argv.slice(2);
const includeUnverifiable = process.argv.includes('--include-unverifiable');

if (!domain || !outfile) {
  console.error('usage: node gen-sources.mjs <domain> <outfile.json> [--include-unverifiable]');
  process.exit(1);
}

// Minimal frontmatter reader: returns { id, claim, status, sources[], usage[] }.
function parseClaim(txt) {
  const fm = txt.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!fm) return null;
  const lines = fm[1].split(/\r?\n/);
  const out = { id: '', claim: '', status: '', sources: [], usage: [] };
  let listKey = null;
  for (const line of lines) {
    const item = line.match(/^\s+-\s+(.*)$/);
    if (listKey && item) {
      out[listKey].push(item[1].trim());
      continue;
    }
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawVal] = kv;
    if (key === 'sources' || key === 'usage') {
      listKey = key;
      continue;
    }
    listKey = null;
    if (key === 'id' || key === 'claim' || key === 'status') {
      out[key] = rawVal.replace(/^"(.*)"$/, '$1').trim();
    }
  }
  return out;
}

// From a usage line, if it belongs to <domain>, return the public routes on it.
// "freeflyevent.com /a, /b — note"           -> ['/a', '/b']
// "freeflyevent.com / — note"                -> ['/']
// "dayonecitizen.com — note (src/data/x.ts)" -> []  (no public route named)
// "freeflyevent-site/src/..."                -> []  (repo path, not this domain)
// "dayonecitizen.com /x — note"              -> []  (only when domain differs)
function routesFor(usageLine, domain) {
  const m = usageLine.match(new RegExp(`^${domain.replace(/\./g, '\\.')}\\s+(.*)$`));
  if (!m) return [];
  let afterDomain = m[1].trim();
  // A leading dash means "note about the domain, no specific route" (e.g. data-file refs).
  if (/^[—–-]/.test(afterDomain)) return [];
  // Keep only the part before the " — " description separator.
  const sepIdx = afterDomain.search(/\s[—–-]\s/);
  let routePart = sepIdx >= 0 ? afterDomain.slice(0, sepIdx) : afterDomain;
  // Drop parentheticals so repo paths inside them can't masquerade as routes.
  routePart = routePart.replace(/\([^)]*\)/g, ' ');
  const tokens = routePart.match(/\/[A-Za-z0-9/_-]*/g) || [];
  return [
    ...new Set(
      tokens
        // Reject file paths (contain "src/" or a .ext) — routes only.
        .filter((t) => !t.includes('src/') && !/\.[A-Za-z0-9]+$/.test(t))
        .map((t) => (t === '/' ? '/' : t.replace(/\/$/, ''))),
    ),
  ];
}

const routes = {};
let claimCount = 0;
for (const f of readdirSync(dir)) {
  if (!f.endsWith('.md') || f === 'README.md') continue;
  const claim = parseClaim(readFileSync(join(dir, f), 'utf8'));
  if (!claim) continue;
  if (claim.status !== 'verified' && !(includeUnverifiable && claim.status === 'unverifiable')) continue;
  const hit = new Set();
  for (const u of claim.usage) for (const r of routesFor(u, domain)) hit.add(r);
  if (!hit.size) continue;
  claimCount++;
  const entry = { id: claim.id, claim: claim.claim, status: claim.status, sources: claim.sources };
  for (const r of hit) (routes[r] ||= []).push(entry);
}

// Stable ordering: routes alphabetically, claims by id within a route.
const orderedRoutes = {};
for (const r of Object.keys(routes).sort()) {
  orderedRoutes[r] = routes[r].sort((a, b) => a.id.localeCompare(b.id));
}

const manifest = {
  note: 'GENERATED by docs/claims/gen-sources.mjs — do not edit by hand. Regenerate after ledger changes.',
  domain,
  routes: orderedRoutes,
};

const outPath = resolve(process.cwd(), outfile);
writeFileSync(outPath, JSON.stringify(manifest, null, 2) + '\n');

const routeCount = Object.keys(orderedRoutes).length;
console.log(`${domain}: ${claimCount} claim(s) across ${routeCount} route(s) -> ${outfile}`);
for (const r of Object.keys(orderedRoutes)) {
  console.log(`  ${r.padEnd(24)} ${orderedRoutes[r].length} claim(s)`);
}
